language: java
jdk:
- openjdk13
services:
- postgresql
before_install:
- psql -c 'create database forum;' -U postgres
sudo: false
after_success:
- bash <(curl -s https://codecov.io/bash)
install: true
script: mvn clean package -DskipTests=true
notifications:
  email:
    recipients:
    - stas.korobeinikov@mail.ru
    on_success: never
    on_failure: always
env:
  global:
  - CODECOV_TOKEN="9848abbc-d81c-4f53-81b3-89e8c7f56a7a"
deploy:
  provider: heroku
  api_key:
    secure: hrFN8roM07E891DVjxtq0h2RBHhar4qsMADzufWNkNTlTDISQmDfiwNSP3KHe3cqwxfp9uHW+Q62hnMzjrDpMGSoV8zs8cbxmEeY638mb1GfNMSfHdZSuIWxQ1S6OtewDa2EaffHYUZNHsL0I8xLNlVrD8/+k6oTTB2Hu8AVJTil4YHz9oOxkMIx9J16xeILMXqPZFsJ6vQmt21Rcdy0d5iD1wlkE358eVQQiJKKpaw/Nk7IUESpYg31AXprVhVZ2ICztNnMlBuEjHFqWGLUNbN6PV1W4zg5saZO1f2A1W6pie3z9wMPaU1MaE/dIVhkXFs/fRvAYzvwDzAi+2SCDZENQedVWNCTdnoQLJ9nusIVxxQ83Nz0MDCyBvlLB37WJQHMCL3IzEs86rWLGsA5Pa08iH98bF8EdoAlJjeR28HPw5vRXWzrElSm/yq5CqaFiEaVIOgX5w2+HiXc4w/ZHHbuKhr94eA5MP/c9gu3JP65jhsHdx91XHV+Zv79Xtndx0pHv1Gxy3tgp1f3g40tPxc3Pp7yLwkec4IFPdVLjuNfwLFSpHOr1Rf1ZWe5sWBNL15K+nSUIqcRQhW150voc/KrbPe+LDPSrX+zJem5VwvJeLGtPiKdQkoOEN3MLPQ8sRaTO2GuXtgitjg9l2p6tHLzdF69/mLNckowawwISbw=
  app: boiling-lake-72040
